services:
  - type: web
    name: fastapi-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.main:app --host=0.0.0.0 --port=8000"
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"

  - type: web
    name: streamlit-frontend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run frontend/streamlit_app.py --server.port 10000"
    envVars:
      - key: BACKEND_URL
        value: "https://fastapi-backend.onrender.com"
